import React from "react";
import Head from "next/head";
import Link from "next/link";
import {
  GetStaticPaths,
  GetStaticProps,
  GetStaticPropsContext,
  NextPage,
} from "next";
import * as Article from "../../features/articles/models/article";
import { Articles } from "../../domain/repositories";
import dayjs from "dayjs";
import { ParsedUrlQuery } from "node:querystring";
import MainLayout from "../../components/Layout/MainLayout/MainLayout";

interface Params extends ParsedUrlQuery {
  id: string;
}

interface Props {
  article: Article.Model;
}

export const getStaticProps: GetStaticProps<Props, Params> = async ({
  params,
}: GetStaticPropsContext) => {
  const article = await Articles.getOne(Number(params?.id));

  return {
    props: {
      article,
    },
  };
};
export const getStaticPaths: GetStaticPaths<Params> = async () => {
  const articles = await Articles.getALl();
  const paths = articles.map((article) => {
    const { id } = article;

    return {
      params: {
        id: id.toString(),
      },
    };
  });

  return { paths, fallback: false };
};

export const ArticleDetail: NextPage<Props> = ({ article }) => {
  const dateFormat = React.useCallback(
    (date: Date) => dayjs().format("YYYY/MM/DD"),
    []
  );

  return (
    <>
      <Head>
        <title>{article.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <h2>{article.title}</h2>
        <p>{dateFormat(article.createdAt)}</p>
        {article.text.blocks.map((block) => {
          return <p key={block.key}>{block.text}</p>;
        })}

        <p>
          <Link href="/">TOPへ</Link>
        </p>
      </MainLayout>
    </>
  );
};

export default ArticleDetail;
