import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import MainLayout from "../components/Layout/MainLayout/MainLayout";
import { Articles } from "../domain/repositories";
import { Article } from "../domain/models";
import dayjs from "dayjs";
import { GetStaticProps, GetStaticPropsContext, NextPage } from "next";

interface Props {
  articles: Article.Model[];
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const articles = await Articles.getALl();
  return {
    props: {
      articles,
    },
  };
};

const Home: NextPage<Props> = ({ articles }) => {
  const dateFormat = React.useCallback(
    (date: Date) => dayjs().format("YYYY/MM/DD"),
    []
  );

  return (
    <>
      <Head>
        <title>ミズイロラボ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <h2>Posts</h2>
        {articles.map((article) => {
          return (
            <div key={article.id} style={{ marginBottom: 20 }}>
              <p>{dateFormat(article.createdAt)}</p>
              <p>
                <Link href={`/article/${article.id}`}>{article.title}</Link>
              </p>
            </div>
          );
        })}
      </MainLayout>
    </>
  );
};

export default Home;
