import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { Inter } from "@next/font/google";
// import styles from "../styles/Home.module.css";
import { Articles } from "../domain/repositories";
import { Article } from "../domain/models";
import dayjs from "dayjs";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [articles, setArticles] = React.useState<Article.Model[]>([]);
  const getArticles = async () => {
    const articles = await Articles.getALl();
    setArticles(articles);
  };
  const dateFormat = React.useCallback(
    (date: Date) => dayjs().format("YYYY/MM/DD"),
    []
  );

  React.useEffect(() => {
    getArticles();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>開発中</p>
        <h1>Memo（仮）</h1>
        <h2>Posts</h2>
        {articles.map((article) => {
          return (
            <div key={article.id} style={{ marginBottom: 20 }}>
              <p>{dateFormat(article.createdAt)}</p>
              <p>
                <Link href={`/article/${article.id}`}>{article.title}</Link>
              </p>
            </div>
          );
        })}
      </main>
    </>
  );
}
